name: aplicacion_maps
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.3+1
  path: ^1.9.0
  google_maps_flutter: ^2.9.0
  permission_handler: ^11.2.0
  geolocator: ^9.0.0
  http: ^1.2.2
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.1.0
  crypto: ^3.0.1
  flutter_rating_bar: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.11

# La sección flutter_icons va aquí, después de las dependencias.
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"  # Imagen del ícono adaptativo

flutter:
  uses-material-design: true

  assets:
    - assets/
